### ISSUE TITLE
The link of the pretrained model is not available

### ISSUE THREAD

**Issue by Yaosui** [Pose-Group/DCPose#1]
Installation step 4

**Comment by FRunyang** [comment]
Hello,  please contact email address：chenhaomingbob@gmail.com
Our pre-train model will be released soon later.

**Comment by Yaosui** [comment]
Thanks a lot!

> Hello, please contact email address：[chenhaomingbob@gmail.com](mailto:chenhaomingbob@gmail.com)
> Our pre-train model will be released soon later.

Thanks a lot!

**Comment by FRunyang** [comment]
In principle, pre-train model dissemination is prohibited, we hope you can respect it. Thanks for understanding!

**Comment by Yaosui** [comment]
> In principle, pre-train model dissemination is prohibited, we hope you can respect it. Thanks for understanding!

This is just for my personal learning  deep learning,and will not disseminate it . At the same time, thank you for your work!
