### ISSUE TITLE
Pose Temporal Merger

### ISSUE THREAD

**Issue by boza-wd** [Pose-Group/DCPose#11]
Hi folks,

thanks for your amazing work.

I have a question regarding the results I have obtained using DCPose.

Below you can see three consecutive images (from a longer sequence). It seems that the temporal component does not correct the false association (left/right knee) which it could have if it used the information from the previous and the next frame. Am I using it in a wrong way, or you expected this kind of behaviour.

![00000040](https://user-images.githubusercontent.com/81355992/121319867-ea24c180-c90c-11eb-99b1-3ddb0b225ed9.jpg)
![00000041](https://user-images.githubusercontent.com/81355992/121319870-eb55ee80-c90c-11eb-9dc5-66ecab206c20.jpg)
![00000042](https://user-images.githubusercontent.com/81355992/121319872-eb55ee80-c90c-11eb-992d-f4e4f3b69d2c.jpg)

Cheers!

**Comment by chenhaomingbob** [comment]
> Hi folks,
> 
> thanks for your amazing work.
> 
> I have a question regarding the results I have obtained using DCPose.
> 
> Below you can see three consecutive images (from a longer sequence). It seems that the temporal component does not correct the false association (left/right knee) which it could have if it used the information from the previous and the next frame. Am I using it in a wrong way, or you expected this kind of behaviour.
> 
> ![00000040](https://user-images.githubusercontent.com/81355992/121319867-ea24c180-c90c-11eb-99b1-3ddb0b225ed9.jpg)
> ![00000041](https://user-images.githubusercontent.com/81355992/121319870-eb55ee80-c90c-11eb-9dc5-66ecab206c20.jpg)
> ![00000042](https://user-images.githubusercontent.com/81355992/121319872-eb55ee80-c90c-11eb-992d-f4e4f3b69d2c.jpg)
> 
> Cheers!

Hi boze-wd:
Sorry, our DCPose occasionally happens the error that discontinuities of human poses, but it works well in most cases.
