### ISSUE TITLE
Change the model

### ISSUE THREAD

**Issue by A7777-gp** [Pose-Group/DCPose#12]
Hello, what should I do if I want to make changes based on the model you published.

**Comment by chenhaomingbob** [comment]
> Hello, what should I do if I want to make changes based on the model you published.

Hi, please feel free to use our code, but please remember to state that your code is adapted from:
Zhenguang Liu, Haoming Chen, Runyang Feng, Shuang Wu, Shouling Ji, Bailin Yang, Xun Wang:
Deep Dual Consecutive Network for Human Pose Estimation, CVPR 2021.

Our code is developed using python-3.6.12, pytorch-1.4.0. You can use Pytorch to modify the code. If you have any question, please feel free to comment.
