### ISSUE TITLE
Questions about additional data

### ISSUE THREAD

**Issue by zhangrj91** [Pose-Group/DCPose#13]
Thank you for your work!

I noticed the result of your model posted on the leaderboard of PoseTrack17 is with additional COCO data.

Could you give more details of using additional data?

Thanks!

**Comment by chenhaomingbob** [comment]
We use the HRNet-W48 pretrained on COCO as our backbone, so the additional dataset is COCO.

**Comment by zhangrj91** [comment]
@chenhaomingbob 
I run the code successfully and I can use your pretrained model to get a result of 82.8 for PoseTrack17 validation dataset, but if I use the provided code and config files to train a new model and the result is only 81.6. 

So I want to know that is there any other settings about the training?

Thanks for your work!

**Comment by FRunyang** [comment]
Please refer to Question https://github.com/Pose-Group/DCPose/issues/16#issuecomment-882043217
