### ISSUE TITLE
Questions about the performance

### ISSUE THREAD

**Issue by zhangrj91** [Pose-Group/DCPose#16]
Thanks for your excellent work!

I run the code successfully and I can use your pretrained model to get a result of 82.8 for PoseTrack17 validation dataset, but if I use the provided code and config files to train a new model and the result is only 81.6.

So I want to know that is there any other settings about the training or the config files about the training are not the updated version?

**Comment by A7777-gp** [comment]
您好，请问一下您使用预训练模型之后是跑的那个代码可以得出81.6的结果？

**Comment by zhangrj91** [comment]
> 您好，请问一下您使用预训练模型之后是跑的那个代码可以得出81.6的结果？

是的

**Comment by FRunyang** [comment]
@zhangrj91 你好，我们推荐直接使用预训练模型即可，因为训练模型时我们未设定死随机种子，初始化比较随机；关于其他配置参数，都已写在配置文件未改动。

**Comment by chenrxi** [comment]
我才复现出80.9mAP
