### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by A7777-gp** [Pose-Group/DCPose#17]
Thank you very much for your work.
I am in China now and I cannot download the posetrack2017 and posetrack2018 dataset. Could you please share it with me?
Or can I train directly with the COCO dataset? What should I do?（Do I need to change the format in COCO？）
Looking forward to your reply ！ Thanks！！

**Comment by FRunyang** [comment]
@A7777-gp  We are sorry to inform you that the problems of network need to be addressed by your self. We download the datasets from the official website: [https://posetrack.net/users/download.php](https://posetrack.net/users/download.php). We have not uploaded it to Baidu-Net-Disk.
