### ISSUE TITLE
模型的速度问题

### ISSUE THREAD

**Issue by MikuuGithub** [Pose-Group/DCPose#18]
在论文中没有找到速度指标的描述，有没有前辈，可以提供下这方面的数据，感谢！

**Comment by FRunyang** [comment]
模型速度和硬件有关，gpu越好越快，具体需要自己测试。

**Comment by MikuuGithub** [comment]
你测试过了吗？可以告诉我一下你的结果吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pose-Group/DCPose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月20日(星期五) 上午9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Pose-Group/DCPose] 模型的速度问题 (#18)





 
模型速度和硬件有关，gpu越好越快，具体需要自己测试。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FRunyang** [comment]
> 你测试过了吗？可以告诉我一下你的结果吗？
> […](#)

我还没测试过，建议你精确测试一下，我们会将结果更新到Readme，十分感谢您的贡献。
