### ISSUE TITLE
模型的速度可以达到实时效果吗

### ISSUE THREAD

**Issue by MikuuGithub** [Pose-Group/DCPose#20]
模型的速度可以达到实时效果吗？

**Comment by FRunyang** [comment]
我们测试过是比较难实现的。

**Comment by MikuuGithub** [comment]
知道了，谢谢您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pose-Group/DCPose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月27日(星期五) 晚上9:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Pose-Group/DCPose] 模型的速度可以达到实时效果吗 (#20)





 
我们测试过是比较难实现的。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
