### ISSUE TITLE
 Can this run on the windows system?

### ISSUE THREAD

**Issue by LiuJiaji1999** [Pose-Group/DCPose#23]
I tried to run on the windows system, but the problem of VC toolkit parsing was always prompted, and the bug still appeared after referring to the solution.How can i solve？？
build\lib.win-amd64-3.6\deform_conv_cuda.cp36-win_amd64.pyd : fatal error LNK1120: 8 个无法解析的外部命令
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120

**Comment by FRunyang** [comment]
We have not run the code on _Windows_ environment. If you can run it well, we encourage you to prepare a guide and we will add it to the readme. 
Thanks in advance.

**Comment by LiuJiaji1999** [comment]
The official website cannot be downloaded, and the result I downloaded from a third-party link is not the same as the catalog？So how to download the PoseTrack dataset?
![423c4b6f8828abd389329acb7608f90](https://user-images.githubusercontent.com/52843642/139617178-cfd98d46-e142-4a00-a966-8871381bc6b2.png)

**Comment by FRunyang** [comment]
We download the datasets in the PoseTrack Official.

**Comment by anas-zafar** [comment]
@LiuJiaji1999 Were you able to run it on windows system?
