### ISSUE TITLE
different video frame，same target？

### ISSUE THREAD

**Issue by LiuJiaji1999** [Pose-Group/DCPose#26]
I would like to ask, yolo only can detect target in a single frame .when defining clip i(p,c,n),by expanding the bounding box by about 25%, the same target between frames at different intervals is cropped. How do you determine the different positions of the same target in different frames? How to cut it?

**Comment by LiuJiaji1999** [comment]
In a video sequence, the same target is in different frames, and the position changes are quite obvious.

**Comment by FRunyang** [comment]
The Pose Temporal Merger (PTM) can aggregate the heatmaps of frames f_p, f_c, and f_n. The Pose Residual Fusion module can also capture the motion dynamics. These are computed based on different positions. Our paper also assumes that the changes between two consecutive frames are not significant.

**Comment by LiuJiaji1999** [comment]
thanks,these days i try to run the code, at the begining I built it according to your operating environment, but when installing DCN, it prompted a version error, so I set up such an environment according to my own GPU,my enviroment is ubuntu18.04+ cuda11.4 +torch1.9, GPU is 3080,And install DCN is finish,but when i run video.py,it hint  ：importError,libcudart.so.10.0  cannot open shared object file:no such file or directory???Crazy, environmental problems prevent the next step

**Comment by FRunyang** [comment]
o k, the version of your pytorch is very high. we use the Pytorch1.5. Deformable convolutions have been intergated to the Pytorch1.8.

**Comment by LiuJiaji1999** [comment]
okay, I try to lower the version,thank you .

**Comment by LiuJiaji1999** [comment]
（ubuntn18.04+cuda10.2+pytorch1.7）Problems encountered in compiling DCN, suggesting that the ninja cannot be used, so I found a way to modify torch/utils/cpp_extension.py ,modify ['ninja'，'-v]' to ['ninja'，'--v']. ['ninja'，'-version'] ['ninja'，'-V'],they all failed

**Comment by FRunyang** [comment]
I suggest you follow our "docs/installation.md" to set your environment. Under this configuration, compilation of DCNV2 can be performed successfully. We have not tested other versions of torch and torchvision.
