### ISSUE TITLE
cannot import name 'deform_conv_cuda' from partially initialized module 'thirdparty.deform_conv' (most likely due to a circular import)

### ISSUE THREAD

**Issue by DWCTOD** [Pose-Group/DCPose#3]
大佬您好，我想运行试一下效果，运行 video.py 的时候报了这个错误，不知道要怎么解决，谢谢啦

cannot import name 'deform_conv_cuda' from partially initialized module 'thirdparty.deform_conv' (most likely due to a circular import)

报错位置：
File "xxx  /  DCPose/thirdparty/deform_conv/functions/deform_conv.py", line 5, in <module>
from .. import deform_conv_cuda

**Comment by chenhaomingbob** [comment]
Hi DWCTOD:
Checking whether the following commands have been executed.
```
cd thirdparty/deform_conv
python setup.py develop
```
If the above command is executed successfully, the files below will be available in the **`thirdparty/deform_conv`** directory.
> deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so
> deform_pool_cuda.cpython-36m-x86_64-linux-gnu.so

**Comment by DWCTOD** [comment]
谢谢大佬的解答，上面的问题解决了
使用  https://drive.google.com/drive/folders/1VPcwo9jVhnJpf5GVwR2-za1PFE6bCOXE 的权重文件好像不能用

![image](https://user-images.githubusercontent.com/41478810/112409003-b1d10680-8d53-11eb-880d-8c2836080eb3.png)

DCPose/tools/inference.py", line 63, in <module>
    model = get_inference_model()
 in get_inference_model
    model_state_dict = {k.replace('module.', ''): v for k, v in checkpoint_dict['state_dict'].items()}
KeyError: 'state_dict'

**Comment by chenhaomingbob** [comment]
这需要模型权重，请发送邮件到chenhaomingbob@gmail.com.

**Comment by ICCV-4228** [comment]
> 谢谢大佬的解答，上面的问题解决了
> 使用 https://drive.google.com/drive/folders/1VPcwo9jVhnJpf5GVwR2-za1PFE6bCOXE 的权重文件好像不能用
> 
> ![image](https://user-images.githubusercontent.com/41478810/112409003-b1d10680-8d53-11eb-880d-8c2836080eb3.png)
> 
> DCPose/tools/inference.py", line 63, in
> model = get_inference_model()
> in get_inference_model
> model_state_dict = {k.replace('module.', ''): v for k, v in checkpoint_dict['state_dict'].items()}
> KeyError: 'state_dict'

我们更新了项目，现在可以直接从 https://drive.google.com/drive/folders/1VPcwo9jVhnJpf5GVwR2-za1PFE6bCOXE 获取模型权重。

**Comment by chenhaomingbob** [comment]
> 谢谢大佬的解答，上面的问题解决了
> 使用 https://drive.google.com/drive/folders/1VPcwo9jVhnJpf5GVwR2-za1PFE6bCOXE 的权重文件好像不能用
> 
> ![image](https://user-images.githubusercontent.com/41478810/112409003-b1d10680-8d53-11eb-880d-8c2836080eb3.png)
> 
> DCPose/tools/inference.py", line 63, in
> model = get_inference_model()
> in get_inference_model
> model_state_dict = {k.replace('module.', ''): v for k, v in checkpoint_dict['state_dict'].items()}
> KeyError: 'state_dict'

我们更新了README文件，可以直接从 https://drive.google.com/drive/folders/1VPcwo9jVhnJpf5GVwR2-za1PFE6bCOXE 获取模型权重。😁

**Comment by DWCTOD** [comment]
太感谢啦，谢谢大佬的分享



在 2021-03-25 19:03:09，"chenhaomingbob" ***@***.***> 写道：

谢谢大佬的解答，上面的问题解决了
使用 https://drive.google.com/drive/folders/1VPcwo9jVhnJpf5GVwR2-za1PFE6bCOXE 的权重文件好像不能用

DCPose/tools/inference.py", line 63, in
model = get_inference_model()
in get_inference_model
model_state_dict = {k.replace('module.', ''): v for k, v in checkpoint_dict['state_dict'].items()}
KeyError: 'state_dict'

我们更新了README文件，可以直接从 https://drive.google.com/drive/folders/1VPcwo9jVhnJpf5GVwR2-za1PFE6bCOXE 获取模型权重。😁

**Comment by DWCTOD** [comment]
大佬您好，请问如果要对多人进行姿态估计的话，要修改哪些地方

**Comment by MikuuGithub** [comment]
> 大佬您好，请问如果要对多人进行姿态估计的话，要修改哪些地方

不需要修改，可以直接进行多人姿态估计
