### ISSUE TITLE
when the pretrained model will release?

### ISSUE THREAD

**Issue by zq1335030905** [Pose-Group/DCPose#4]
Hi, thanks for your great job, I'm working on gait recognition, and I want to extract human skeletons accurately. I run on the demo, but it doesn't work because of the lack of the yolov3.weight this file. Thanks again!

**Comment by FRunyang** [comment]
Hello, I have uploaded the Pretrained model to the google driver: https://drive.google.com/file/d/11DH3cpjG_OQP0ja0-WilTT0LlR6S8pw7/view?usp=sharing
