### ISSUE TITLE
posetrack download

### ISSUE THREAD

**Issue by Yulv-git** [Pose-Group/DCPose#41]
您好，PoseTrack官网目前已无法访问，方便分享下PoseTrack17、PoseTrack18的数据集及其标注文件吗？
谢谢~

**Comment by 1223s** [comment]
请问你找到数据集了吗

**Comment by Ared521** [comment]
> PoseTrack官网目前已无法访问
请问你找到了吗

**Comment by Yulv-git** [comment]
> 您好，PoseTrack官网目前已无法访问，方便分享下PoseTrack17、PoseTrack18的数据集及其标注文件吗？ 谢谢~

This link may be available for download. https://hyper.ai/datasets/5729

**Comment by gjgjgjfff** [comment]
> 您好，PoseTrack官网目前已无法访问，方便分享下PoseTrack17、PoseTrack18的数据集及其标注文件吗？ 谢谢~

您好，请问您找到数据集了吗？
期待您的回复！

**Comment by Ared521** [comment]
> > 您好，PoseTrack官网目前已无法访问，方便分享下PoseTrack17、PoseTrack18的数据集及其标注文件吗？ 谢谢~
> 
> 您好，请问您找到数据集了吗？ 期待您的回复！

没呢。咋办呀

**Comment by wxhqw** [comment]
have some solution to download the posetrack dataset

**Comment by Yulv-git** [comment]
Finish with https://github.com/Pose-Group/DCPose/issues/41#issuecomment-1319383284 & https://hyper.ai/datasets/5729.
