### ISSUE TITLE
复现

### ISSUE THREAD

**Issue by A7777-gp** [Pose-Group/DCPose#5]
有两个问题想问一下作者，万分感谢！1.数据集下载的时候，比如posetrack18要全部下载完吗？2.posetrack17的脚本怎么用？

**Comment by chenhaomingbob** [comment]
你好！

### 问题1
回答： 要将数据集全部下载下来，否则无法在posetrack18数据集上运行

### 问题2:
回答：运行 https://github.com/facebookresearch/DetectAndTrack/blob/master/tools/gen_posetrack_json.py ，将posetrack17图片重命名并保存到 `images_renamed`   目录下。

**Comment by A7777-gp** [comment]
谢谢！
