### ISSUE TITLE
hi ,bro.how can i run code using my own video?

### ISSUE THREAD

**Issue by qhdqhd** [Pose-Group/DCPose#8]
```
cd demo/                   
mkdir input/
# Put your video in the input directory
python video.py
```

Your method above didnt work.Maybe because the pretrained model (pretrained_coco_model)is not suitable?
thanks a lot !

**Comment by chenhaomingbob** [comment]
Hi qhdqhd :
   I've tested my code and it works fine. Posting your error message and I will help you.

**Comment by qhdqhd** [comment]
Thank you,chenhaomingbob:
`(DCPose) qhd@qhd-Lenovo:~/0code/pose/DCPose-main/demo$ python video.py
Traceback (most recent call last):
  File "video.py", line 13, in <module>
    from tools.inference import inference_PE
  File "/home/qhd/0code/pose/DCPose-main/tools/inference.py", line 64, in <module>
    model = get_inference_model()
  File "/home/qhd/0code/pose/DCPose-main/tools/inference.py", line 58, in get_inference_model
    model_state_dict = {k.replace('module.', ''): v for k, v in checkpoint_dict['state_dict'].items()}
KeyError: 'state_dict'
`
I use `pretrained_coco_model.pth` in google drive https://drive.google.com/drive/folders/1RYwOsNDsCZAsJe44MnpwHmwA3GSTDcAr

**Comment by qhdqhd** [comment]
@chenhaomingbob  this is my error, it seems that the pretrained model is not  suitable ?

**Comment by chenhaomingbob** [comment]
Hi @qhdqhd: 
You should use pre-trained weights:  `posetrack17_dcpose.pth`.
As the following code is written:  https://github.com/Pose-Group/DCPose/blob/078f4495c654f7220fa599fda07a8eef5dc54f21/tools/inference.py#L33

**Comment by qhdqhd** [comment]
Thankyou, I find  `PoseTrack17_DCPose.pth` just now,  it is a little unremarkable.  @chenhaomingbob
