### ISSUE TITLE
YOLOv3 

### ISSUE THREAD

**Issue by libo-coder** [Pose-Group/DCPose#9]
请问您一下，您使用的 YOLOv3 检测训练代码有吗

**Comment by chenhaomingbob** [comment]
抱歉@libo-coder ，我们并没有训练YOLOv3作为Human Detector.
为了保证公平的比较，在PoseTrack数据集的训练阶段，我们沿用 [posewarper](https://github.com/facebookresearch/PoseWarper) 提供的BBox检测结果，相关[issue](https://github.com/facebookresearch/PoseWarper/issues/15).

**Comment by libo-coder** [comment]
OK ，谢谢  目前在看您的关键点检测训练代码，在数据加载方面我不了解训练 json 文件中的 image 和 annotation 之间的对应关系，可以说一下吗？

**Comment by chenhaomingbob** [comment]
json文件是参考coco格式制作的。image里面是单张图片的属性（比如，图片路径，图片大小，帧的序号），annotation里面是单人pose的属性（比如，pose属于哪张图片，pose包含的关键点坐标）。
因为我们是多人姿态估计人物，一张图片会包含多个人，所以 1个 image item 会对应 n个  annotation item。

**Comment by libo-coder** [comment]
嗯嗯，这个我看出来了，不清楚的是怎么判定 annotation 中的关键点信息是对应的 image 标注信息的呢？我本以为根据的是 id 属性，但我看了一下，发现也不是

**Comment by chenhaomingbob** [comment]
annotation 里面有个属性是 image_id, 与 image 里面的 id 对应。

**Comment by libo-coder** [comment]
OK  我再来看一下  非常感谢
